---
languageCode: en-us
baseurl: https://jnyman.com/
title: JNyman.com
#    Hamsters Byte
description: A blog on programming.
# theme: nofancy
theme: beautifulhugo

author:
  name: Jon Nyman
  github: jon49
  linkedin: eenyman
  twitter: NymanJon

permalinks:
  post: /:year/:month/:day/:filename/
  page: /:filename/

disqusShortname: "jnyman-com"
menu:
    main:
        - name: Blog
          url: ""
          weight: 1
        - name: About
          url: about/
          weight: 2
        - name: Tags
          url: tags/
          weight: 3
---
