---
languageCode: en-us
baseurl: http://jnyman.com/
title: Hamsters Byte
description: A blog on programming.
theme: nofancy

author:
  name: Jon Nyman
  github: jon49
  linkedin: eenyman
  twitter: NymanJon

permalinks:
  post: /:year/:month/:day/:filename/
  page: /:filename/

disqusShortname: "jnyman-com"
---
